version: 2

registries:
  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/atulin/index.json
    token: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: "bun"
    directory: "/Ogma3/FrontendCode"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"